apiVersion: apps/v1
kind: Deployment

metadata:
  name: k8s-cicd-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: k8s-cicd-app

  template:
    metadata:
      labels:
        app: k8s-cicd-app

    spec:
      containers:
        - name: k8s-cicd-app

          image: unisanashra/k8s-cicd-app

          ports:
            - containerPort: 80
